// --------------------------------------------------------------------
// FILE:    sv_file.cpp
// SOURCE:  CLI-004
// STATUS:  WORKING
// UPDATED: 2026-08-26
// CONTACT: Jeff Nye
// --------------------------------------------------------------------
#include "sv_file.h"

namespace cgen
{

// --------------------------------------------------------------------
SvFile::SvFile(const std::string &name,
               const std::string &system_name,
               const std::string &source_file,
               Kind kind)
  : name_(name), system_(system_name), source_(source_file), kind_(kind)
{
}

// --------------------------------------------------------------------
std::string SvFile::lead() const
{
  return kind_ == Kind::Sv ? "//" : "#";
}

// --------------------------------------------------------------------
void SvFile::ln(const std::string &s)
{
  size_t end = s.size();
  while(end > 0 && (s[end - 1] == ' ' || s[end - 1] == '\t')) --end;
  body_.append(s, 0, end);
  body_ += '\n';
}

// --------------------------------------------------------------------
void SvFile::lines(const std::vector<std::string> &v)
{
  for(const std::string &s : v) ln(s);
}

// --------------------------------------------------------------------
void SvFile::bar()
{
  std::string s = lead();
  while(int(s.size()) < Width) s += '-';
  ln(s);
}

// --------------------------------------------------------------------
void SvFile::note(const std::string &s)
{
  ln(lead() + " " + s);
}

// --------------------------------------------------------------------
// R-11. The same bytes for the same configuration, every run.
// --------------------------------------------------------------------
std::string SvFile::head() const
{
  const std::string c = lead();
  std::string h;

  h += c + " SPDX-License-Identifier: Apache-2.0\n";
  h += c + " Copyright (c) 2026 Jeff Nye, uarchlabs.com\n";
  h += c + " SPDX-FileCopyrightText: 2026 Jeff Nye <jeff@uarchlabs.com>\n";

  std::string b = c;
  while(int(b.size()) < Width) b += '-';
  h += b + "\n";

  h += c + " FILE:      " + name_ + "\n";
  h += c + " GENERATED  This file is generated by cgen. DO NOT HAND\n";
  h += c + "            EDIT. Every edit is lost the next time the\n";
  h += c + "            configuration is emitted. Change the\n";
  h += c + "            configuration and emit again.\n";
  h += c + " TOOL:      cgen " + std::string(VERSION) + "\n";
  h += c + " SOURCE:    system '" + system_ + "', from " + source_ + "\n";
  h += b + "\n";

  return h;
}

// --------------------------------------------------------------------
void SvFile::set_prefix(const std::string &snake,
                        const std::string &camel)
{
  snake_ = snake;
  camel_ = camel;
}

// --------------------------------------------------------------------
// Types and functions take the snake prefix, constants the camel one.
// Anything not on this list is module local and cannot collide.
// --------------------------------------------------------------------
const std::vector<std::string> &SvFile::members()
{
  static const std::vector<std::string> m = {
    // types and functions, snake
    "addr_t", "tag_t", "set_t", "way_t", "line_t", "word_t",
    "beat_t", "bank_t", "repl_state_t",
    "mshr_t", "req_id_t", "tgt_vec_t",
    "tag_of", "set_of", "bank_of", "offset_of", "word_of",
    "line_base", "line_addr",
    "repl_victim", "repl_update", "repl_rank",
    // constants, camel
    "PaBits", "CapacityBytes", "LineBytes", "LineBits", "Ways",
    "Banks", "Sets", "SetsPerBank", "BytesPerWay",
    "OffsetBits", "IndexBits", "TagBits", "BankBits", "SetIdxBits",
    "WayBits", "OffsetLsb", "OffsetMsb", "IndexLsb", "IndexMsb",
    "TagLsb", "TagMsb", "BankLsb", "BankMsb", "SetIdxLsb",
    "SetIdxMsb", "AddrUnitBytes", "WordBytes", "WordBits",
    "WordsPerLine", "WordIdxBits", "WordIdxLsb", "WordIdxMsb",
    "BeatBits", "BeatBytes", "Beats", "BeatIdxBits",
    "ReplBits", "ReplReset", "ReplStates", "ReplVictimTable",
    "ReplUpdateTable", "RankBits", "AddrBits",
    "Mshrs", "MshrTargets", "MshrIdxBits", "MshrTgtBits",
    "MshrCntBits", "ReqIdBits", "MaxOutstanding", "QualReserve",
    "ReadLatency", "CmpStage", "PipePad"
  };
  return m;
}

namespace {

bool ident_char(char c)
{
  return (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') ||
         (c >= '0' && c <= '9') || c == '_';
}

} // namespace

// --------------------------------------------------------------------
std::string SvFile::content() const
{
  if(snake_.empty()) return head() + body_;

  // whole identifiers only, so LineBytes is not found inside
  // LineBytesSomething and a comment reading "8 ways" is untouched
  std::string out;
  out.reserve(body_.size() + body_.size() / 4);

  size_t i = 0;
  while(i < body_.size()) {
    if(!ident_char(body_[i]) ||
       (i > 0 && ident_char(body_[i - 1]))) {
      out += body_[i++];
      continue;
    }
    size_t j = i;
    while(j < body_.size() && ident_char(body_[j])) ++j;
    const std::string tok = body_.substr(i, j - i);

    bool hit = false;
    for(const std::string &m : members()) {
      if(m != tok) continue;
      const bool snake = m.find('_') != std::string::npos ||
                         (m[0] >= 'a' && m[0] <= 'z');
      out += (snake ? snake_ : camel_) + tok;
      hit = true;
      break;
    }
    if(!hit) out += tok;
    i = j;
  }

  return head() + out;
}

} // namespace cgen
